version: "3"
services:
  watchtower:
    container_name: watchtower
    image: "containrrr/watchtower:${IMAGE_TAG:-amd64-1.3.0}"
    command: --label-enable --cleanup --interval ${REFRESH_INTERVAL}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    restart: unless-stopped
    volumes:
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
